import json, os

cells = [
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "# CIR-ARC-3B: Distributed TPU Training Harness (3.000B Parameters)\n",
            "### Kaggle TPU VM (TPU v5e-8 / TPU v3-8) Production Run\n",
            "\n",
            "- **Parameters**: Exactly 3,000,000,000 across 10 cognitive faculties.\n",
            "- **Trunk**: 24-Layer GQA (20Q / 5KV, d=2560) + SwiGLU (d_ff=6912) with 2D/1D RoPE.\n",
            "- **Precision**: Native bfloat16 on Matrix Multiplication Units (MXUs).\n",
            "- **Memory Optimization**: Adafactor optimizer (< 1 GB state) + Gradient Checkpointing.\n",
            "- **Dataset**: Multi-Source ARC sublevel transitions (29,280 samples)."
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# Cell 1: Clone Repository & Setup Environment\n",
            "import os, sys, shutil\n",
            "\n",
            "# Clean and clone latest master branch\n",
            "shutil.rmtree('/kaggle/working/CIR-ARC', ignore_errors=True)\n",
            "!git clone --depth 1 -b master https://github.com/Kapilraj-13/CIR-ARC.git /kaggle/working/CIR-ARC\n",
            "\n",
            "repo_src = '/kaggle/working/CIR-ARC/src'\n",
            "if repo_src not in sys.path:\n",
            "    sys.path.insert(0, repo_src)\n",
            "\n",
            "print('[SUCCESS] Repository cloned and src path configured!')"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# Cell 2: Connect to TPU Hardware Accelerator\n",
            "import torch\n",
            "import torch_xla.core.xla_model as xm\n",
            "import torch_xla.distributed.parallel_loader as pl\n",
            "\n",
            "device = xm.xla_device()\n",
            "print(f'[TPU CONNECTED] Active Device: {device} ({xm.xla_device_hw(device)})')\n",
            "print(f'PyTorch Version: {torch.__version__}')"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# Cell 3: Verify 3,000,000,000 Parameter Budget (Zero-RAM Meta Audit)\n",
            "from cir_arc.neural.models.cir_arc_3b import CirArc3B, CirArc3BConfig\n",
            "\n",
            "model_config = CirArc3BConfig()\n",
            "\n",
            "with torch.device('meta'):\n",
            "    model_audit = CirArc3B(model_config)\n",
            "counts = model_audit.count_parameters()\n",
            "\n",
            "print('=' * 65)\n",
            "print(f\"{'Cognitive Faculty':<35} | {'Exact Parameters':>18}\")\n",
            "print('-' * 65)\n",
            "for k, v in counts.items():\n",
            "    print(f\"{k:<35} | {v:18,d}\")\n",
            "print('=' * 65)\n",
            "assert counts['total'] == 3_000_000_000, f\"Mismatch: {counts['total']}\"\n",
            "print('\\n[CONFIRMED] Audited parameter count: Exactly 3,000,000,000 parameters.')\n",
            "del model_audit"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# Cell 4: Multi-Source Dataset Loader (train_sublevels.jsonl)\n",
            "import glob, json\n",
            "from torch.utils.data import Dataset, DataLoader\n",
            "\n",
            "class TransitionDataset(Dataset):\n",
            "    def __init__(self, data_file=None):\n",
            "        self.records = []\n",
            "        if not data_file or not os.path.exists(data_file):\n",
            "            candidates = [\n",
            "                '/kaggle/input/datasets/kapilrajr/cir-arc-model-data/train_sublevels.jsonl',\n",
            "                '/kaggle/input/cir-arc-model-data/train_sublevels.jsonl',\n",
            "                '/kaggle/input/datasets/kapilrajr/CIR ARC-MODEL-DATA/train_sublevels.jsonl',\n",
            "                '/kaggle/input/CIR ARC-MODEL-DATA/train_sublevels.jsonl',\n",
            "            ]\n",
            "            for c in candidates:\n",
            "                if os.path.exists(c):\n",
            "                    data_file = c\n",
            "                    break\n",
            "            if not data_file:\n",
            "                wild = glob.glob('/kaggle/input/**/train_sublevels.jsonl', recursive=True)\n",
            "                data_file = wild[0] if wild else None\n",
            "                \n",
            "        if data_file and os.path.exists(data_file):\n",
            "            sz_mb = os.path.getsize(data_file) / 1e6\n",
            "            print(f'Loading data from {data_file} ({sz_mb:.2f} MB)...')\n",
            "            with open(data_file, 'r', encoding='utf-8') as f:\n",
            "                for line in f:\n",
            "                    line_str = line.strip()\n",
            "                    if line_str:\n",
            "                        self.records.append(json.loads(line_str))\n",
            "            print(f'[SUCCESS] Loaded {len(self.records):,d} training samples.')\n",
            "        else:\n",
            "            print('Warning: No data file found. Creating in-memory samples.')\n",
            "            for i in range(1000):\n",
            "                self.records.append({'grid': [[i % 9]*16 for _ in range(16)], 'action': i % 8, 'is_negative_example': False})\n",
            "\n",
            "    def __len__(self):\n",
            "        return len(self.records)\n",
            "\n",
            "    def __getitem__(self, idx):\n",
            "        rec = self.records[idx]\n",
            "        gt = rec.get('grid', [[0]*16 for _ in range(16)])\n",
            "        gn = rec.get('next_grid', gt)\n",
            "        \n",
            "        t_in = torch.zeros(11, 32, 32, dtype=torch.float32)\n",
            "        t_out = torch.zeros(11, 32, 32, dtype=torch.float32)\n",
            "        \n",
            "        ht, wt = min(len(gt), 32), min(len(gt[0]) if len(gt) > 0 else 0, 32)\n",
            "        for r in range(ht):\n",
            "            for c in range(wt):\n",
            "                t_in[int(gt[r][c]) % 10, r, c] = 1.0\n",
            "                \n",
            "        hn, wn = min(len(gn), 32), min(len(gn[0]) if len(gn) > 0 else 0, 32)\n",
            "        for r in range(hn):\n",
            "            for c in range(wn):\n",
            "                t_out[int(gn[r][c]) % 10, r, c] = 1.0\n",
            "                \n",
            "        action = int(rec.get('action', 0)) % 4102\n",
            "        is_neg = 1.0 if rec.get('is_negative_example', False) else 0.0\n",
            "        return {'grid_t': t_in, 'grid_next': t_out, 'action': torch.tensor(action, dtype=torch.long), 'is_negative': torch.tensor(is_neg, dtype=torch.float32)}\n",
            "\n",
            "train_ds = TransitionDataset()\n",
            "print(f'[DATASET READY] Total samples available: {len(train_ds):,d}')"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# Cell 5: Full Production TPU Training Loop (5 Epochs)\n",
            "import time, math, os\n",
            "import torch.nn.functional as F\n",
            "from torch.utils.data import DataLoader\n",
            "from torch.optim import Adafactor\n",
            "from cir_arc.neural.models.cir_arc_3b import CirArc3B, CirArc3BConfig\n",
            "\n",
            "# 1. Instantiate 3.000B Model in bfloat16 on TPU\n",
            "print('[1/4] Loading 3,000,000,000 parameters in bfloat16 on TPU...', flush=True)\n",
            "torch.set_default_dtype(torch.bfloat16)\n",
            "model = CirArc3B(CirArc3BConfig()).to(device)\n",
            "torch.set_default_dtype(torch.float32)\n",
            "print('      [SUCCESS] 3.000B model loaded into TPU HBM!', flush=True)\n",
            "\n",
            "# 2. High-Throughput Data Loader\n",
            "batch_size = 2\n",
            "grad_accum = 8  # Effective batch size = 16\n",
            "train_loader = DataLoader(train_ds, batch_size=batch_size, shuffle=True, drop_last=True)\n",
            "xla_loader = pl.ParallelLoader(train_loader, [device]).per_device_loader(device)\n",
            "\n",
            "# 3. Adafactor Optimizer (< 1 GB State)\n",
            "print('[2/4] Initializing Adafactor optimizer (< 1 GB state)...', flush=True)\n",
            "optimizer = Adafactor(model.parameters(), lr=2e-4, weight_decay=0.1)\n",
            "print('      [SUCCESS] Adafactor optimizer configured.', flush=True)\n",
            "\n",
            "checkpoint_dir = '/kaggle/working/checkpoints/cir_arc_3b'\n",
            "os.makedirs(checkpoint_dir, exist_ok=True)\n",
            "\n",
            "# 4. Multi-Task Objective Loss Function\n",
            "def compute_loss(model_out, batch):\n",
            "    l_policy = F.cross_entropy(model_out['policy_logits'], batch['action'].to(device))\n",
            "    l_safety = F.binary_cross_entropy(model_out['entrapment_risk'].squeeze(-1), batch['is_negative'].to(device))\n",
            "    l_dynamics = F.mse_loss(model_out['world_model']['predicted_state'], model_out['cognitive_state'].detach())\n",
            "    total = l_policy + 0.5 * l_safety + 0.25 * l_dynamics\n",
            "    return total, l_policy, l_safety\n",
            "\n",
            "# 5. Training Loop\n",
            "num_epochs = 5\n",
            "save_interval_steps = 250\n",
            "global_step = 0\n",
            "model.train()\n",
            "\n",
            "print('\\n' + '=' * 65, flush=True)\n",
            "print(f'[3/4] STARTING CIR-ARC-3B TPU TRAINING ({num_epochs} Epochs)', flush=True)\n",
            "print('=' * 65, flush=True)\n",
            "\n",
            "for epoch in range(num_epochs):\n",
            "    epoch_start = time.time()\n",
            "    print(f'\\n>>> Epoch {epoch + 1}/{num_epochs} Started...', flush=True)\n",
            "    optimizer.zero_grad()\n",
            "    accum_loss = 0.0\n",
            "\n",
            "    for step, batch in enumerate(xla_loader):\n",
            "        grid_t = batch['grid_t'].to(device).to(torch.bfloat16)\n",
            "        grid_next = batch['grid_next'].to(device).to(torch.bfloat16)\n",
            "        action = batch['action'].to(device)\n",
            "\n",
            "        out = model(grid_t=grid_t, grid_next=grid_next, action=action, gradient_checkpointing=True)\n",
            "        loss, p_loss, s_loss = compute_loss(out, batch)\n",
            "        loss = loss / grad_accum\n",
            "        loss.backward()\n",
            "        accum_loss += loss.item() * grad_accum\n",
            "\n",
            "        if (step + 1) % grad_accum == 0:\n",
            "            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)\n",
            "            xm.optimizer_step(optimizer)\n",
            "            xm.mark_step()\n",
            "            optimizer.zero_grad()\n",
            "            global_step += 1\n",
            "\n",
            "            if global_step % 25 == 0:\n",
            "                print(f'Step {global_step:05d} | Loss: {accum_loss:.4f} | Policy: {p_loss.item():.4f} | Safety: {s_loss.item():.4f}', flush=True)\n",
            "            accum_loss = 0.0\n",
            "\n",
            "            if global_step % save_interval_steps == 0:\n",
            "                ckpt_path = os.path.join(checkpoint_dir, f'cir_arc_3b_step{global_step}.pt')\n",
            "                xm.save(model.state_dict(), ckpt_path)\n",
            "                print(f'--> [Saved Checkpoint]: {ckpt_path}', flush=True)\n",
            "\n",
            "    print(f'>>> Epoch {epoch + 1} finished in {time.time() - epoch_start:.2f}s', flush=True)\n",
            "\n",
            "# Final Weights Save\n",
            "final_ckpt = os.path.join(checkpoint_dir, 'cir_arc_3b_final.pt')\n",
            "xm.save(model.state_dict(), final_ckpt)\n",
            "print(f'\\n[DONE] CIR-ARC-3B Training Finished! Saved to: {final_ckpt}', flush=True)"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# Cell 6: Inspect Saved Checkpoints\n",
            "import glob, os\n",
            "ckpts = glob.glob('/kaggle/working/checkpoints/cir_arc_3b/*.pt')\n",
            "print(f'Generated Checkpoints ({len(ckpts)}):')\n",
            "for c in sorted(ckpts):\n",
            "    sz_mb = os.path.getsize(c) / 1e6\n",
            "    print(f'  --> {os.path.basename(c)}: {sz_mb:.2f} MB')"
        ]
    }
]

nb = {
    "cells": cells,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.10.12"}
    },
    "nbformat": 4,
    "nbformat_minor": 5
}

target_paths = [
    r"d:\AI_Projects\CIR-ARC\notebooks\kaggle_tpu_training_cir_arc_3b.ipynb",
    r"D:\Downloads\notebooka352e8a93e.ipynb"
]

for p in target_paths:
    os.makedirs(os.path.dirname(p), exist_ok=True)
    with open(p, "w", encoding="utf-8") as f:
        json.dump(nb, f, indent=2)
    print(f"Successfully wrote clean production notebook to: {p}")
